# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='pair_id',
        ),
    ]
