# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='input_files'),
        ),
    ]
